<?php
// Copyright (C) 2014 Lance

// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation; either version 2 of the License, or (at your option) any later
// version.

// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

// You should have received a copy of the GNU General Public License along with
// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
// Place, Suite 330, Boston, MA 02111-1307 USA

/**
 * Implements hook_help().
 */
function uc_taxes_nc_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#uc_taxes_nc":
      $output = '<p>'.  t("Calculate North Carolina Sales Tax") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implement hook_calculate_tax().
 */
function uc_taxes_nc_calculate_tax( $order ) {
  global $user;

  if( is_numeric( $order ))
  {
    $order = uc_order_load( $order );
  }
  if( !is_object( $order ))
  {
    return array();
  }

  return array();
}
